# Exercise 2: Sinusoids and the DFT

This exercise builds intuition for the main operations behind the Discrete Fourier Transform (DFT). It has five parts:
1. Generate a real sinusoid
2. Generate a complex sinusoid
3. Implement the DFT
4. Implement the IDFT
5. Compute the magnitude spectrum of a sequence

### Relevant concepts

A real sinusoid in discrete time can be written as:

\begin{equation}
x[n] = A\cos(2 \pi fnT + \varphi)
\end{equation}

where $x$ is a real-valued sequence, $n$ is the time index, $A$ is amplitude, $f$ is frequency in Hz, $T = 1/fs$ is the sampling period, $fs$ is sampling frequency in Hz, and $\varphi$ is initial phase in radians.

A complex sinusoid in discrete time can be written as:

\begin{equation}
\bar{x}[n] = Ae^{j(\omega nT + \varphi)} = A\cos(\omega nT + \varphi) + jA\sin(\omega nT + \varphi)
\end{equation}

where $\omega = 2\pi f$ is angular frequency in radians/second.

The $N$-point DFT of a sequence $x$ is:

\begin{equation}
X[k] = \sum_{n=0}^{N-1} x[n]e^{-j2\pi kn/N}, \quad k=0,\ldots,N-1
\end{equation}

The IDFT of a spectrum $X$ is:

\begin{equation}
x[n] = \frac{1}{N}\sum_{k=0}^{N-1} X[k]e^{j2\pi kn/N}, \quad n=0,\ldots,N-1
\end{equation}

The magnitude spectrum is the absolute value of the complex spectrum: $|X[k]|$.

## Part 1 – Generate a real sinusoid

The function `gen_sine()` should generate a real sinusoid (using `np.cos`) from:
- amplitude `A`
- frequency `f` (Hz)
- initial phase `phi` (radians)
- sampling rate `fs` (Hz)
- duration `t` (seconds)

Assume `A > 0`, `t > 0`, `fs > 0`, and `fs > 2f` to avoid aliasing.

Return a NumPy array `x` containing the generated sinusoid samples.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import IPython.display as ipd

In [ ]:
# E2 - 1.1: Complete function gen_sine()

def gen_sine(A, f, phi, fs, t):
    """Generate a real sinusoid from amplitude, frequency, phase, sampling rate, and duration.

    Args:
        A (float): amplitude of the sinusoid
        f (float): frequency in Hz
        phi (float): initial phase in radians
        fs (float): sampling rate in Hz
        t (float): duration in seconds

    Returns:
        np.array: generated sinusoid samples
    """
    ### Your code here


If you call `gen_sine()` with `A=1.0`, `f=10.0`, `phi=1.0`, `fs=50`, and `t=0.1`, the output should be:

```
array([ 0.54030231, -0.63332387, -0.93171798,  0.05749049,  0.96724906])
```

To hear a sinusoid, use a longer duration and higher sampling rate. For example: `A=1.0`, `f=440.0`, `phi=1.0`, `fs=5000`, `t=0.5`, then play it with:

`ipd.display(ipd.Audio(data=x, rate=fs))`

In [ ]:
# E2 - 1.2: Call gen_sine() with the values above, then plot and play the output sinusoid

### Your code here

**E2 - 1.3: Conceptual questions (answer here)**
1. Set `phi=0` and then `phi=pi/2` with the same `A`, `f`, `fs`, and `t`. How does the waveform change in time? Explain using the cosine equation.
2. Try `f=20 Hz` and `f=30 Hz` at `fs=50 Hz`. Which one violates Nyquist, and what do you observe in the plotted signal?

## Part 2 – Generate a complex sinusoid

The function `gen_complex_sine()` should generate a complex sinusoid used by the DFT, of length `N`, at frequency index `k`.

In DFT computation we use the conjugate complex exponential, but this function should generate the base complex sinusoid itself.

Use:
- amplitude = `1`
- length = `N`
- angular frequency = `2*pi*k/N`

Inputs are positive integers `k` and `N` with `k < N`. Return `c_sine` as a NumPy array of complex values, using `np.exp()`.

In [ ]:
# E2 - 2.1: Complete function gen_complex_sine()

def gen_complex_sine(k, N):
    """Generate one complex sinusoid used in DFT analysis.

    Args:
        k (int): frequency-bin index
        N (int): DFT length (number of samples)

    Returns:
        np.array: complex sinusoid of length N
    """
    ### Your code here

If you run `gen_complex_sine(k=1, N=5)`, it should return:

```
array([ 1.        +0.j        ,  0.30901699+0.95105652j,
       -0.80901699+0.58778525j, -0.80901699-0.58778525j,
        0.30901699-0.95105652j])
```

In [ ]:
# E2 - 2.2: Call gen_complex_sine() with k=1 and N=5,
#            then plot real and imaginary parts of the output.

### Your code here

**E2 - 2.3: Conceptual questions (answer here)**
1. Compute (or estimate from your plot) the phase increment between consecutive samples. How does it relate to `2*pi*k/N`?
2. Compare `k=1` and `k=N-1` for the same `N`. What relationship do you observe between their real/imaginary parts, and why?

## Part 3 – Implement the discrete Fourier transform (DFT)

The function `dft()` should implement the DFT equation above.

Given a sequence `x` of length `N`, return its spectrum `X` of length `N`, with frequency-bin indices from `0` to `N-1`.

In [ ]:
# E2 - 3.1: Complete function dft()

def dft(x):
    """Compute the N-point DFT of a sequence.

    Args:
        x (np.array): input sequence of length N

    Returns:
        np.array: DFT spectrum of x (length N)
    """
    ### Your code here

If you run `dft()` with `x = np.array([1, 2, 3, 4])`, it should return:

```
array([10.0 + 0.0j, -2.0 + 2.0j, -2.0 - 9.79717439e-16j, -2.0 - 2.0j])
```

You may not obtain exact zeros due to floating-point precision. Values around `1e-15` are numerical error and can be treated as zero.

In [ ]:
# E2 - 3.2: Call dft() with x = [1, 2, 3, 4],
#            then plot real and imaginary parts of the output spectrum.

### Your code here

**E2 - 3.3: Conceptual questions (answer here)**

1. In your own words, what does each DFT bin `X[k]` measure about the input signal?
2. For `x=[1,2,3,4]`, identify which bin corresponds to the DC component and verify it numerically from your output.
3. Compare your `dft(x)` output with `np.fft.fft(x)` for one test case of your choice. Are they the same (up to numerical precision)? If not, explain where they differ.

## Part 4 – Implement the inverse discrete Fourier transform (IDFT)

The function `idft()` should implement the IDFT equation above.

Given a frequency spectrum `X` of length `N`, return its time-domain sequence `x` (also length `N`). Assume frequency-bin indices range from `0` to `N-1`.

Remember to apply the `1/N` scaling factor.

In [ ]:
# E2 - 4.1: Complete function idft()

def idft(X):
    """Compute the N-point IDFT of a spectrum.

    Args:
        X (np.array): input spectrum of length N

    Returns:
        np.array: IDFT of X (length N)
    """
    ### Your code here

If you run `idft()` with `X = np.array([1, 1, 1, 1])`, the output should be close to:

```
array([ 1.00000000e+00+0.00000000e+00j, -4.59242550e-17+5.55111512e-17j,
        0.00000000e+00+6.12323400e-17j,  8.22616137e-17+8.32667268e-17j])
```

This is essentially `[1, 0, 0, 0]`, with tiny floating-point residuals. As a validation, you can compute `dft(idft(X))` and check that it returns the original `X` (up to numerical error).

In [ ]:
# E2 - 4.2: Plot real/imaginary parts of X = [1, 1, 1, 1], call idft(),
#            plot real/imaginary parts of the output sequence,
#            then compute dft() of that output to validate reconstruction.

### Your code here

**E2 - 4.3: Conceptual questions (answer here)**

1. Why does the IDFT include the factor `1/N` while the DFT (as implemented here) does not?
2. Use one example where you compute `x_hat = idft(dft(x))`. How close is `x_hat` to `x`? Report the maximum absolute error.
3. Your IDFT output may contain tiny imaginary residuals for real signals. Why do these appear, and when is it safe to discard them with `np.real(...)`?

## Part 5 – Compute the magnitude spectrum

The function `gen_mag_spec()` should compute the magnitude spectrum of an input sequence `x` of length `N`.

Return an `N`-point magnitude spectrum with frequency-bin indices from `0` to `N-1`.

In [ ]:
# E2 - 5.1: Complete function gen_mag_spec()

def gen_mag_spec(x):
    """Compute magnitude spectrum of a sequence.

    Args:
        x (np.array): input sequence of length N

    Returns:
        np.array: magnitude spectrum of x (length N)
    """
    ### Your code here

If you run `gen_mag_spec()` with `x = np.array([1, 2, 3, 4])`, it should return:

```
array([10.0, 2.82842712, 2.0, 2.82842712])
```

For a more realistic case, use a longer input such as:

`x = np.cos(2*np.pi*200.0*np.arange(512)/1000)`

Then plot both input and output using `plt.plot(x)` and `plt.plot(X)`.

In [ ]:
# E2 - 5.2: Plot the input cosine signal, call gen_mag_spec(), and plot the output magnitude spectrum.
#            Validate that the spectral peak matches the sinusoid frequency.

### Your code here

**E2 - 5.3: Conceptual questions (answer here)**

1. From your magnitude spectrum plot, report the bin index of the main peak and convert it to frequency in Hz. Compare with the sinusoid frequency used to generate the signal.
2. Explain why the spectrum of a real cosine shows two symmetric peaks (positive and negative frequency bins in the DFT indexing).
3. Change the sinusoid amplitude from `1.0` to `0.5` (keeping everything else fixed). How does the magnitude spectrum change? Quantify the change in peak magnitude.
4. If the sinusoid frequency is not exactly at a DFT bin center, what effect do you observe in the spectrum? Describe it and explain why it happens.